### PR TITLE
Unify all NVIC circuits for a single web-proof circuit

### LINKED ISSUE #19: create NIVC implementation with `aes-proof` + `parser-attestor` circuits
# Mission
Now that we have all the circuits needed in this repository, we should create an NIVC chain that uses `aes-proof` AES-GCTR implementation alongside the `parser-attestor` plaintext http locking +  json parsing scheme.

## Tasks
- [ ] Modify all the NIVC circuits to adopt the same parameters: `DATA_BYTES` and `MAX_STACK_HEIGHT`. Note that some circuits such as `JsonMaskObjectNIVC` will need a specific `maxKeyLen`. We should use `DATA_BYTES` and `MAX_STACK_HEIGHT` as parameters that define the `step_in/out` size for ALL NIVC circuits! `TOTAL_BYTES_ACROSS_NIVC` should not be necessary to have as an input as the calculation is given in the JSON parser template:
```
assert(MAX_STACK_HEIGHT >= 2);
    var PER_ITERATION_DATA_LENGTH = MAX_STACK_HEIGHT * 2 + 2;
    var TOTAL_BYTES_ACROSS_NIVC   = DATA_BYTES * (PER_ITERATION_DATA_LENGTH + 1) + 1;
``` 
- [ ] Write a test that tests the flow between `aes-proof` and `parser-attestor` circuits works properly for the set `DATA_SIZE`

---

For `MAX_STACK_HEIGHT`, 10 seems reasonable. For a test feel free to use smaller to make this faster.

### PR DESCRIPTION
**Pull request by 0xJepsen**
All circuits are accounted for. I added one missing test: `test/http/locker.test.ts`. There are some tests that have been omitted because they rely on codegen. The tests and diffs not accounted for are here:

- [circuits/test/spotify_top_artists.test.ts](https://github.com/pluto/parser-attestor/blob/main/circuits/test/spotify_top_artists.test.ts)
- [circuits/test/json/extractor/extractor.test.ts](https://github.com/pluto/parser-attestor/blob/main/circuits/test/json/extractor/extractor.test.ts)
- [This unused line](https://github.com/pluto/parser-attestor/blob/fab64305777ab422287bc2d8aa95f8805c80e7d8/circuits/test/json/extractor/interpreter.test.ts#L2)
- [circuits/test/http/codegen.test.ts](https://github.com/pluto/parser-attestor/blob/main/circuits/test/http/codegen.test.ts)

The [circuits/utils/array.circom](https://github.com/pluto/parser-attestor/blob/main/circuits/utils/array.circom) and [circuits/utils/bytes.circom](https://github.com/pluto/parser-attestor/blob/main/circuits/utils/bytes.circom) utils are not missing anything but but do have some additional utilities that i added when i added the aes stuff. 

Moving forward i will
- [x] Create main circuit that wires all our circuits together following the order: AES -> HTTP Parse -> http lock header -> http body mask -> json parse -> json_mask_object/json_mask_array -> extract value
- [ ] Create end-to-end test for this.

Closes #19

### CODE REVIEW

**Comment by 0xJepsen** [comment]
Taking a lunch break now but good progress so far on this.

**Comment by Autoparallel** [comment]
> Create main circuit that wires all our circuits together following the order: AES -> HTTP Parse -> http lock header -> http body mask -> json parse -> json_mask_object/json_mask_array -> extract value

This doesn't make sense, we can't do this. We need to have separate circuits to fold!

Happy to meet and explain this more if need be.

**Comment by Autoparallel** [comment]
Just FYI, this has a massive regression in circuit constraints.

I was seeing roughly 1.2M constraints for AESGCTR for 320 bytes of plaintext.

I have addressed this on a separate branch.

**Comment by Autoparallel** [comment]
Closing in favor of #24

**Pull request closed without merging**
