### PR TITLE
chore: merge parser attestor

### LINKED ISSUE #9: bring in parser-attestor

### PR DESCRIPTION
**Pull request by lonerapier**
closes #9 
- brings in history from parser-attestor
- remove codegen cli and corresponding circuit tests

### CODE REVIEW

**Comment by devloper** [comment]
@0xJepsen @lonerapier  It feels like the strategy between these two PRs should be the same 

https://github.com/pluto/web-prover-circuits/pull/8 => Is moving the parser-attestor into this repo
https://github.com/pluto/web-prover-circuits/pull/11 => Is referencing the standalone aes-proof

Both seem viable to me, I'm personally lightly leaning toward waylon's approach here, because it helps to keep useful packages to other teams in standalone repository (good for our "github seo"). 

But ultimately I think you can both choose the approach, we should just pick one.

**Comment by Autoparallel** [comment]
I'm okay with either way to do it personally.

**Comment by lonerapier** [comment]
i'm also in favor of just keeping only the circuits useful for web-prover and rest of the low level circuits in separate repos.

But i'm not sure if the development workflow will be optimal. Any change in the web-prover will depend upon 2 releases in parser-attestor/aes-proof and then this repo.

**Comment by Autoparallel** [comment]
I'm of the opinion that we either completely combine these repos and deprecate/archive the old, or we do something super minimal like have just a `package.json` and re-export the circuits here.

Truth be told, I don't care much, but if I were to pick, I'd just combine repos and remove the fluff we have. E.g., we can archive the codegen.

**Review by Autoparallel — APPROVED** [review]
Seems like a correct start to me.

Let's minimize this more from here as we can.

**Pull request merged**
