### PR TITLE
feat: NIVC hash chain

### LINKED ISSUE #38: feat: NIVC Hash Chain
Pass a hashchain value through AES and into the subsequent circuits where the hashchain will be computed again.

### PR DESCRIPTION
**Pull request by Autoparallel**
WIP 

Working to reduce public io signals to 1, just pass a hashchain value through AES and into the subsequent circuits where the hashchain will be computed again.

--- 

I am using circomkit a bit more to help see constraint counts and what not as I'm going through and I've found we have a good bit of warnings again.

- [x] SHOULD MAKE AN ISSUE.
Closes #38 

---
- [x] AES should also take in CT and verify it.

### CODE REVIEW

**Comment by Autoparallel** [comment]
Currently fighting a bug where circomkit isn't getting the `step_out` value from the circuit. I know it's computing properly, but it isn't giving me it in TypeScript:
```
it("NIVC_CHAIN", async () => {
       //..
        let parseAndLockStartLine = await httpParseAndLockStartLineCircuit.compute({ step_in: temp_step_in, data: http_response_plaintext, beginning: beginningPadded, beginning_length: beginning.length, middle: middlePadded, middle_length: middle.length, final: finalPadded, final_length: final.length }, ["step_out"]); // THIS GIVES ME `[]` `"step_out"` even though I can see it's correct with circom logs. 
```
This is in the `NIVC_FULL` test

**Comment by 0xJepsen** [comment]
okay so i added the aes ciphertext validation to the nvic full. I also fixed aes tests that are now passing. Will work on getting the rest of test suite to pass but i know less about how to debug these circuits.

**Comment by Autoparallel** [comment]
Did you guys just finish this up for me 🥹

**Comment by 0xJepsen** [comment]
> Did you guys just finish this up for me 🥹

yes <3

**Comment by Autoparallel** [comment]
LET'S FUCKING MERGE IT THEN

**Pull request merged**
