### PR TITLE
feat: download artifact and attach at release

### PR DESCRIPTION
**Pull request by lonerapier**
creates a new release with `semantic-release` and attach the artifact generated during pull request.

previous workflow generated the artifact but was not working with semantic release.

But due to semantic release, we'll have to follow conventional commits. Can revert this and use manual version management as per discussion.

### CODE REVIEW

**Review by Autoparallel — COMMENTED** [review]
Can you explain what changes this makes? And perhaps attach this to an issue?

**Comment by lonerapier** [comment]
@Autoparallel added some info regarding the PR, and linked an issue for better discussion. Thanks for pointing this out.

**Comment by Autoparallel** [comment]
Bah... I really want to keep this simple. Conventional commits seems like a weird choice of overhead to me, though I'm not totally against it.

I think the thing is here that we will likely never use a patch version at all. Version changes here are going to be large.

**Review by Autoparallel — APPROVED** [review]
Perfect! Nice and simple.

**Pull request merged**
